using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SnapDocs.Domain.Entities;
using SnapDocs.Infrastructure.Persistence;
using SnapDocs.Web.Models;

namespace SnapDocs.Web.Controllers;

public class BrandingController : Controller
{
    private static readonly Guid DemoCompanyId = Guid.Parse("11111111-1111-1111-1111-111111111111");
    private readonly SnapDocsDbContext _db;
    private readonly IWebHostEnvironment _environment;

    public BrandingController(SnapDocsDbContext db, IWebHostEnvironment environment)
    {
        _db = db;
        _environment = environment;
    }

    public async Task<IActionResult> Index()
    {
        var model = await BuildModelAsync();
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Save(BrandingViewModel model)
    {
        if (!ModelState.IsValid)
        {
            await EnrichModelAsync(model);
            return View("Index", model);
        }

        var company = await _db.Companies.FirstAsync(x => x.Id == DemoCompanyId);
        var branding = await _db.CompanyBrandings.FirstOrDefaultAsync(x => x.CompanyId == DemoCompanyId);
        if (branding == null)
        {
            branding = new CompanyBranding { CompanyId = DemoCompanyId };
            _db.CompanyBrandings.Add(branding);
        }

        branding.CompanyName = string.IsNullOrWhiteSpace(model.CompanyName) ? company.Name : model.CompanyName.Trim();
        branding.PrimaryColor = NormalizeColor(model.PrimaryColor, "#2563EB");
        branding.SecondaryColor = NormalizeColor(model.SecondaryColor, "#1E293B");
        branding.SuccessColor = NormalizeColor(model.SuccessColor, "#22C55E");
        branding.DangerColor = NormalizeColor(model.DangerColor, "#EF4444");
        branding.WarningColor = NormalizeColor(model.WarningColor, "#F59E0B");
        branding.FontFamily = string.IsNullOrWhiteSpace(model.FontFamily) ? "Cairo" : model.FontFamily.Trim();
        branding.ThemeName = string.IsNullOrWhiteSpace(model.ThemeName) ? "Corporate" : model.ThemeName.Trim();
        branding.Radius = string.IsNullOrWhiteSpace(model.Radius) ? "22px" : model.Radius.Trim();
        branding.DarkMode = model.DarkMode;
        branding.WhiteLabel = model.WhiteLabel;
        branding.FooterText = model.FooterText;
        branding.LoginWelcomeText = model.LoginWelcomeText;
        branding.UpdatedAtUtc = DateTime.UtcNow;

        company.Name = branding.CompanyName;
        company.ThemeColor = branding.PrimaryColor;
        company.LogoUrl = branding.LogoPath;
        company.UpdatedAtUtc = DateTime.UtcNow;

        if (model.Logo != null)
        {
            branding.LogoPath = await SaveUploadAsync(model.Logo, "logo");
            company.LogoUrl = branding.LogoPath;
        }

        if (model.Favicon != null)
        {
            branding.FaviconPath = await SaveUploadAsync(model.Favicon, "favicon");
        }

        if (model.LoginBackground != null)
        {
            branding.LoginBackgroundPath = await SaveUploadAsync(model.LoginBackground, "login-bg");
        }

        _db.ActivityLogs.Add(new ActivityLog
        {
            CompanyId = DemoCompanyId,
            ActorName = User.Identity?.Name ?? "System",
            Action = "تحديث الهوية البصرية",
            EntityName = "Branding",
            EntityNumber = branding.ThemeName,
            Notes = $"تم تحديث Theme الشركة إلى {branding.ThemeName}"
        });

        await _db.SaveChangesAsync();
        TempData["Success"] = "تم حفظ الهوية البصرية بنجاح.";
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Reset()
    {
        var branding = await _db.CompanyBrandings.FirstOrDefaultAsync(x => x.CompanyId == DemoCompanyId);
        if (branding != null)
        {
            branding.PrimaryColor = "#2563EB";
            branding.SecondaryColor = "#1E293B";
            branding.SuccessColor = "#22C55E";
            branding.DangerColor = "#EF4444";
            branding.WarningColor = "#F59E0B";
            branding.FontFamily = "Cairo";
            branding.ThemeName = "Corporate";
            branding.Radius = "22px";
            branding.DarkMode = false;
            branding.WhiteLabel = false;
            branding.FooterText = "Generated by SnapDocs";
            branding.UpdatedAtUtc = DateTime.UtcNow;
            await _db.SaveChangesAsync();
        }

        TempData["Success"] = "تمت استعادة الإعدادات الافتراضية.";
        return RedirectToAction(nameof(Index));
    }

    private async Task<BrandingViewModel> BuildModelAsync()
    {
        var company = await _db.Companies.AsNoTracking().FirstAsync(x => x.Id == DemoCompanyId);
        var branding = await _db.CompanyBrandings.AsNoTracking().FirstOrDefaultAsync(x => x.CompanyId == DemoCompanyId);

        var model = new BrandingViewModel
        {
            Id = branding?.Id,
            CompanyId = DemoCompanyId,
            CompanyName = branding?.CompanyName ?? company.Name,
            CurrentLogoPath = branding?.LogoPath ?? company.LogoUrl,
            CurrentFaviconPath = branding?.FaviconPath,
            CurrentLoginBackgroundPath = branding?.LoginBackgroundPath,
            PrimaryColor = branding?.PrimaryColor ?? "#2563EB",
            SecondaryColor = branding?.SecondaryColor ?? "#1E293B",
            SuccessColor = branding?.SuccessColor ?? "#22C55E",
            DangerColor = branding?.DangerColor ?? "#EF4444",
            WarningColor = branding?.WarningColor ?? "#F59E0B",
            FontFamily = branding?.FontFamily ?? "Cairo",
            ThemeName = branding?.ThemeName ?? "Corporate",
            Radius = branding?.Radius ?? "22px",
            DarkMode = branding?.DarkMode ?? false,
            WhiteLabel = branding?.WhiteLabel ?? false,
            FooterText = branding?.FooterText,
            LoginWelcomeText = branding?.LoginWelcomeText
        };
        await EnrichModelAsync(model);
        return model;
    }

    private Task EnrichModelAsync(BrandingViewModel model)
    {
        model.Fonts = new[] { "Cairo", "Tajawal", "IBM Plex Sans Arabic", "Segoe UI", "Inter" };
        model.Themes = new[] { "Corporate", "Classic", "Modern", "Minimal", "Retail", "Medical", "Restaurant", "Construction" };
        return Task.CompletedTask;
    }

    private async Task<string> SaveUploadAsync(IFormFile file, string prefix)
    {
        var extension = Path.GetExtension(file.FileName);
        var safeExtension = string.IsNullOrWhiteSpace(extension) ? ".bin" : extension.ToLowerInvariant();
        var folder = Path.Combine(_environment.WebRootPath, "uploads", "company", DemoCompanyId.ToString("N"));
        Directory.CreateDirectory(folder);
        var fileName = $"{prefix}-{DateTime.UtcNow:yyyyMMddHHmmssfff}{safeExtension}";
        var path = Path.Combine(folder, fileName);
        await using var stream = System.IO.File.Create(path);
        await file.CopyToAsync(stream);
        return $"/uploads/company/{DemoCompanyId:N}/{fileName}";
    }

    private static string NormalizeColor(string? value, string fallback)
    {
        if (string.IsNullOrWhiteSpace(value)) return fallback;
        var trimmed = value.Trim();
        return trimmed.StartsWith('#') ? trimmed : $"#{trimmed}";
    }
}
