using SnapDocs.Domain.Common;

namespace SnapDocs.Domain.Entities;

public class CompanyBranding : BaseEntity
{
    public Guid CompanyId { get; set; }
    public Company? Company { get; set; }

    public string CompanyName { get; set; } = string.Empty;
    public string? LogoPath { get; set; }
    public string? FaviconPath { get; set; }
    public string? LoginBackgroundPath { get; set; }

    public string PrimaryColor { get; set; } = "#2563EB";
    public string SecondaryColor { get; set; } = "#1E293B";
    public string SuccessColor { get; set; } = "#22C55E";
    public string DangerColor { get; set; } = "#EF4444";
    public string WarningColor { get; set; } = "#F59E0B";

    public string FontFamily { get; set; } = "Cairo";
    public string ThemeName { get; set; } = "Corporate";
    public string Radius { get; set; } = "22px";
    public bool DarkMode { get; set; }
    public bool WhiteLabel { get; set; }

    public string? FooterText { get; set; } = "Generated by SnapDocs";
    public string? LoginWelcomeText { get; set; } = "ادخل إلى مساحة عمل شركتك";
}
